# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb646d1b7e6e3851703ea29e06b150e4556536013dacd9741643684d64d40c00086a25ec1362c1985207984a5c3f8309e3ef352e35b71530f8f46ea003fd994

test:
  secret_key_base: bf61bdbd4a88fe581bc57bffb8e514dd2eb27f05649ed4bd98f0824f3ab5f84773078bf22bafc5d527ca3504034ee6631d99d77dabebe412809e69ab8e767618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
